name: Deploy Core Crawling to Lightsail Container

on:
  push:
    branches: [ main ]
    paths:
      - 'core_crawling/**'

env:
  AWS_REGION: ap-northeast-2
  CONTAINER_SERVICE_NAME: core-crawling-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build and push image to Lightsail
      env:
        PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
        BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
        CORE_PORT: ${{ secrets.CORE_PORT }}
      run: |
        cd core_crawling
        aws lightsail push-container-image \
          --service-name $CONTAINER_SERVICE_NAME \
          --label core-crawling \
          --image core-crawling:latest